DROP TABLE [dbo].[Images]
DROP TABLE [dbo].[SUPItems]
DROP TABLE [dbo].[SUPUsers]
DROP TABLE [dbo].[AspNetUserRoles]
DROP TABLE [dbo].[AspNetUserClaims]
DROP TABLE [dbo].[AspNetUserLogins]
DROP TABLE [dbo].[AspNetRoles]
DROP TABLE [dbo].[AspNetUsers]